### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by javatarz** [ryanoglesby08/the-eod-machine#1]
Is it possible to publish the EOD machine with all its dependencies in a docker image with the possibility to mount the configuration file into a mount point?

**Comment by ryanoglesby08** [comment]
Hey Karun!

I don't see why not! That would be a great distribution mechanism. 👍 

I am not actively working on EOD machine right now though, so I'd happily welcome a PR to add that.

**Comment by javatarz** [comment]
Oh, I intended to submit a PR. I just wanted to check if you had any objections to it.

Is there a build pipeline for this project already or should I create one myself? :)

**Comment by ryanoglesby08** [comment]
Perfect.

No build pipeline. Go for it! Let me know if I need to activate any Github integrations or install any bots.

**Comment by ryanoglesby08** [comment]
@javatarz I beat you to it, we may use EOD Machine on my current project. 😄 

🐳 https://hub.docker.com/r/ryanoglesby08/eod-machine/
