### ISSUE TITLE
Project management tool links support

### ISSUE THREAD

**Issue by mrveera** [ryanoglesby08/the-eod-machine#3]
## Context :  Ability to support project management cards link by identifying card number from update
We can have a configuration for `project management issue link` and `regular expression` to identify the number in  EOD Update.

For example: 
   Configuration: `issues_link`:`https://github.com/ryanoglesby08/the-eod-machine/issues/`
   Update: ` Added ability to edit eod update #2` 
   Email:  Added ability to edit eod update [#2](https://github.com/ryanoglesby08/the-eod-machine/issues/2)

I can do PR quickly for this.

**Comment by ryanoglesby08** [comment]
This does seem useful, but I'm wondering how to handle the various project management tools as they seem to have different URL schemes. Github is very easy, but other tools are different.

For example:
Jira: <https://my-organization.atlassian.net/browse/SOMEPROJECT-95>
Trello: <https://trello.com/c/ksHyye5K>

I suppose with Jira it would be fine and you would put #SOMEPROJECT-95 in your update. Trello seems not as user friendly though...

Perhaps the updates should support rich text formatting or markdown as a more flexible solution, then people can embed links easily.

Thoughts?

**Comment by veera83372** [comment]
Yeah. WYSIWYG editor  instead just text input box would be more helpful than having just project management link.
